version: '3.8'

services:
  # SQL Server Service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: si_ola_app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql_server;Database=Test;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

# Volumes to persist SQL Server data
volumes:
  sql_data:

# Networks to connect the services
networks:
  app-network:
    driver: bridge
